---
- name: Destroy an Assisted Installer provisioned OpenShift Cluster
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cluster_id: ""
    infraenv_id: ""
    cluster_status: ""
    deployment_name: ""
    compiled_uri_headers:
      User-Agent: AnsibleAutomation/4.2
    generated_asset_directory: "./generated_assets"
    delete_generated_assets: true

  tasks:
    - name: Read in variables
      ansible.builtin.include_vars:
        dir: vars
        extensions:
          - 'yaml'
          - 'yml'

    # =========================================================================================================================
    # Preflight
    # =========================================================================================================================

    - name: Initial Preflight Checks
      ansible.builtin.include_tasks: tasks/preflight/main.yaml
      tags:
        - preflight

    - name: Preflight Check, AI Service - Set up Authentication Headers if needed
      when: assisted_service_authentication != "none"
      ansible.builtin.include_tasks: tasks/ai-svc/setup_auth_headers.yaml
      tags:
        - preflight
        - ai_setup_headers

    - name: Preflight Check, AI Service - Version Checks
      ansible.builtin.include_tasks: tasks/ai-svc/query_openshift_versions.yaml
      tags:
        - preflight
        - ai_query_versions

    # =========================================================================================================================
    # Preflight Infrastructure Connection Tests
    # =========================================================================================================================

    - name: Preflight Check - Libvirt Connection Test
      when: provider.type == "libvirt"
      ansible.builtin.include_tasks: tasks/preflight/conntest_libvirt.yaml
      tags:
        - preflight
        - conntest_libvirt
      loop: "{{ infrastructure_providers }}"
      loop_control:
        loop_var: provider

    - name: Preflight Check - Nutanix Connection Test
      when: provider.type == "nutanix"
      ansible.builtin.include_tasks: tasks/preflight/conntest_nutanix.yaml
      loop: "{{ infrastructure_providers }}"
      loop_control:
        loop_var: provider
      tags:
        - preflight
        - conntest_nutanix

    - name: Preflight Check - VMWare Connection Test
      when: provider.type == "vsphere"
      ansible.builtin.include_tasks: tasks/preflight/conntest_vmware.yaml
      loop: "{{ infrastructure_providers }}"
      loop_control:
        loop_var: provider
      tags:
        - preflight
        - conntest_vmware

    # =========================================================================================================================
    # Assisted Installer Service - Cluster and InfraEnv checks
    # =========================================================================================================================

    - name: AI Service - Check for existing cluster
      ansible.builtin.uri:
        headers: "{{ compiled_uri_headers }}"
        url: "{{ assisted_service_endpoint }}/clusters"
        return_content: true
        method: GET
      register: read_clusters
      tags:
        - ai_svc
        - ai_svc_query_clusters

    - name: AI Service - Check for existing infraenvs
      ansible.builtin.uri:
        headers: "{{ compiled_uri_headers }}"
        url: "{{ assisted_service_endpoint }}/infra-envs"
        return_content: true
        method: GET
      register: read_infraenvs
      tags:
        - ai_svc
        - ai_svc_query_infraenvs

    - name: Set facts if cluster exists
      when: (cluster_item.base_dns_domain is defined) and ((cluster_item.base_dns_domain == cluster_domain) and (cluster_item.name == cluster_name))
      ansible.builtin.set_fact:
        cluster_id: "{{ cluster_item.id }}"
        cluster_status: "{{ cluster_item.status }}"
      loop: "{{ read_clusters.json }}"
      loop_control:
        loop_var: cluster_item
        label: "Cluster ID: {{ cluster_item.id }}"
      tags:
        - ai_svc
        - ai_svc_set_cluster

    - name: Set facts if infraenv exists
      when: (infraenv_item.cluster_id is defined) and (infraenv_item.cluster_id == cluster_id) and (infraenv_item.name == cluster_name)
      ansible.builtin.set_fact:
        infraenv_id: "{{ infraenv_item.id }}"
        infraenv_download_url: "{{ infraenv_item.download_url }}"
      loop: "{{ read_infraenvs.json }}"
      loop_control:
        loop_var: infraenv_item
        label: "InfraEnv ID: {{ infraenv_item.id }}"
      tags:
        - ai_svc
        - ai_svc_set_infraenv

    # =========================================================================================================================
    # Infrastructure-specific Destruction Tasks - Libvirt
    # =========================================================================================================================

    - name: Create the list of Libvirt targeted hosts
      ansible.builtin.set_fact:
        libvirt_hosts: "{{ libvirt_hosts | default([]) + [node_item] }}"
        unique_libvirt_infra_providers: []
      loop: "{{ cluster_nodes }}"
      loop_control:
        loop_var: node_item
      when: node_item.infra.type == "libvirt"
      tags:
        - infra_libvirt
        - infra_libvirt_create_hosts_list

    - name: Create the list of unique Libvirt infrastructure providers
      when: libvirt_hosts is defined and libvirt_hosts | length > 0
      ansible.builtin.include_tasks: tasks/infra-libvirt/get_unique_providers.yaml
      loop: "{{ libvirt_hosts }}"
      loop_control:
        loop_var: node_item
      tags:
        - infra_libvirt
        - infra_libvirt_create_infra_list

    - name: Delete the Libvirt infrastructure
      when:
        - libvirt_hosts is defined
        - libvirt_hosts | length > 0
        - unique_libvirt_infra_providers | length > 0
      tags:
        - infra_libvirt
        - infra_libvirt_destroy_infra
      block:
        - name: Delete infrastructure
          ansible.builtin.include_tasks: tasks/infra-libvirt/destroy.yaml
          loop: "{{ libvirt_hosts }}"
          loop_control:
            loop_var: node_item
            label: "Libvirt Host: {{ node_item.name }}"
          tags:
            - infra_libvirt_delete_infra

        - name: Perform per Libvirt Infrastructure Provider destruction
          ansible.builtin.include_tasks: tasks/infra-libvirt/per_provider_delete.yaml
          loop: "{{ unique_libvirt_infra_providers }}"
          loop_control:
            loop_var: provider
            label: "Libvirt Infrastructure Provider: {{ provider.name }}"
          tags:
            - infra_libvirt_per_provider_delete

    # =========================================================================================================================
    # Infrastructure-specific Destruction Tasks - Nutanix
    # =========================================================================================================================

    - name: Create the list of Nutanix targeted hosts
      when: node_item.infra.type == "nutanix"
      tags:
        - infra_nutanix
        - infra_nutanix_create_hosts_list
      ansible.builtin.set_fact:
        nutanix_hosts: "{{ nutanix_hosts | default([]) + [node_item] }}"
        unique_nutanix_infra_providers: []
      loop: "{{ cluster_nodes }}"
      loop_control:
        loop_var: node_item

    - name: Create the list of unique Nutanix infrastructure providers
      when: nutanix_hosts is defined and nutanix_hosts | length > 0
      tags:
        - infra_nutanix
        - infra_nutanix_create_infra_list
      ansible.builtin.include_tasks: tasks/infra-nutanix/get_unique_providers.yaml
      loop: "{{ nutanix_hosts }}"
      loop_control:
        loop_var: node_item

    - name: Delete the Nutanix infrastructure
      when:
        - nutanix_hosts is defined
        - nutanix_hosts | length > 0
        - unique_nutanix_infra_providers | length > 0
      tags:
        - infra_nutanix
        - infra_nutanix_destroy_infra
      block:
        - name: Delete infrastructure
          ansible.builtin.include_tasks: tasks/infra-nutanix/destroy.yaml
          loop: "{{ nutanix_hosts }}"
          loop_control:
            loop_var: node_item
            label: "Nutanix Host: {{ node_item.name }}"
          tags:
            - infra_nutanix_delete_infra

        - name: Perform per Nutanix Infrastructure Provider destruction
          ansible.builtin.include_tasks: tasks/infra-nutanix/per_provider_delete.yaml
          loop: "{{ unique_nutanix_infra_providers }}"
          loop_control:
            loop_var: provider
            label: "Nutanix Infrastructure Provider: {{ provider.name }}"
          tags:
            - infra_nutanix_per_provider_delete

    # =========================================================================================================================
    # Infrastructure-specific Destruction Tasks - vSphere
    # =========================================================================================================================

    - name: Create the list of vSphere targeted hosts
      when: node_item.infra.type == "vsphere"
      tags:
        - infra_vsphere
        - infra_vsphere_create_hosts_list
      ansible.builtin.set_fact:
        vsphere_hosts: "{{ vsphere_hosts | default([]) + [node_item] }}"
        unique_vsphere_infra_providers: []
      loop: "{{ cluster_nodes }}"
      loop_control:
        loop_var: node_item

    - name: Create the list of unique vSphere infrastructure providers
      when: vsphere_hosts is defined and vsphere_hosts | length > 0
      tags:
        - infra_vsphere
        - infra_vsphere_create_infra_list
      ansible.builtin.include_tasks: tasks/infra-vsphere/get_unique_providers.yaml
      loop: "{{ vsphere_hosts }}"
      loop_control:
        loop_var: node_item

    - name: Delete the vSphere infrastructure
      when:
        - vsphere_hosts is defined
        - vsphere_hosts | length > 0
        - unique_vsphere_infra_providers | length > 0
      tags:
        - infra_vsphere
        - infra_vsphere_destroy_infra
      block:
        - name: Delete infrastructure
          ansible.builtin.include_tasks: tasks/infra-vsphere/destroy.yaml
          loop: "{{ vsphere_hosts }}"
          loop_control:
            loop_var: node_item
            label: "vSphere Host: {{ node_item.name }}"
          tags:
            - infra_vsphere_delete_infra

        - name: Perform per vSphere Infrastructure Provider destruction
          ansible.builtin.include_tasks: tasks/infra-vsphere/per_provider_delete.yaml
          loop: "{{ unique_vsphere_infra_providers }}"
          loop_control:
            loop_var: provider
            label: "vSphere Infrastructure Provider: {{ provider.name }}"
          tags:
            - infra_vsphere_per_provider_delete

    # =========================================================================================================================
    # Assisted Installer Service - Delete InfraEnv
    # =========================================================================================================================

    - name: Delete the infraenv from the Assisted Installer service
      when: infraenv_id != ""
      tags:
        - ai_svc
        - ai_svc_remove_infraenv
      block:
        - name: Get the list of hosts from the API
          ansible.builtin.uri:
            headers: "{{ compiled_uri_headers }}"
            url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}/hosts"
            return_content: true
            method: GET
            status_code: 200
          register: ai_svc_list_of_hosts
          tags:
            - ai_svc_get_hosts

        - name: Delete the hosts from the infraenv
          ansible.builtin.uri:
            headers: "{{ compiled_uri_headers }}"
            url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}/hosts/{{ host_item.id }}"
            return_content: true
            method: DELETE
            status_code: 204
          loop: "{{ ai_svc_list_of_hosts.json }}"
          loop_control:
            loop_var: host_item
            label: "Host ID: {{ host_item.id }}"
          tags:
            - ai_svc_delete_hosts

        - name: Delete the infraenv
          ansible.builtin.uri:
            headers: "{{ compiled_uri_headers }}"
            url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}"
            return_content: true
            method: DELETE
            status_code: 204
            body_format: json
          register: delete_infraenv
          ignore_errors: true
          tags:
            - ai_svc_delete_infraenv

    # =========================================================================================================================
    # Assisted Installer Service - Delete Cluster
    # =========================================================================================================================

    - name: Delete the cluster from the Assisted Installer service
      when: cluster_id != ""
      tags:
        - ai_svc
        - ai_svc_remove_cluster
      block:
        - name: Cancel the cluster just in case
          ansible.builtin.uri:
            headers: "{{ compiled_uri_headers }}"
            url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/actions/cancel"
            return_content: true
            method: POST
            status_code: 202
            body_format: json
          register: cancel_cluster
          ignore_errors: true
          tags:
            - ai_svc_cancel_cluster

        - name: Reset the cluster just in case
          ansible.builtin.uri:
            headers: "{{ compiled_uri_headers }}"
            url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/actions/reset"
            return_content: true
            method: POST
            status_code: 202
            body_format: json
          register: reset_cluster
          ignore_errors: true
          tags:
            - ai_svc_reset_cluster

        - name: Delete the cluster
          ansible.builtin.uri:
            headers: "{{ compiled_uri_headers }}"
            url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}"
            return_content: true
            method: DELETE
            status_code: 204
            body_format: json
          register: delete_cluster
          ignore_errors: true
          tags:
            - ai_svc_delete_cluster

    # =========================================================================================================================
    # Delete local cluster files
    # =========================================================================================================================

    - name: Delete the generated content directory
      when: delete_generated_assets | bool and cluster_id != ""
      ansible.builtin.file:
        state: absent
        path: "{{ generated_asset_directory }}/{{ cluster_id }}/"
      tags:
        - delete_generated_content
