---
- name: Get the cluster credentials
  uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/credentials"
    return_content: yes
    method: GET
    status_code: 200
    body_format: json
  register: cluster_credentials_query

- name: Get the cluster Kubeconfig
  uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/downloads/credentials?file_name=kubeconfig"
    return_content: yes
    method: GET
    status_code: 200
    body_format: json
  register: cluster_kubeconfig_query

- name: Set cluster credential facts
  set_fact:
    cluster_api_url: "{{ (cluster_kubeconfig_query.content|from_yaml).clusters[0].cluster.server }}"
    cluster_console_url: "{{ cluster_credentials_query.json.console_url }}"
    cluster_kubeadmin_username: "{{ cluster_credentials_query.json.username }}"
    cluster_kubeadmin_password: "{{ cluster_credentials_query.json.password }}"
    cluster_kubeconfig: "{{ cluster_kubeconfig_query.content | from_yaml }}"

- name: Save Kubeconfig file
  copy:
    content: "{{ cluster_kubeconfig | to_yaml }}"
    dest: "{{ generated_asset_directory }}/{{ cluster_id }}/kubeconfig"

- name: Show credentials
  debug:
    msg: "Console URL: {{ cluster_console_url }} --- {{ cluster_kubeadmin_username }} / {{ cluster_kubeadmin_password }} @ {{ cluster_api_url }}"
